// T6 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool
#include clientscripts\mp\_utility;
#include clientscripts\mp\zombies\_zm_utility;

main_start()
{
    if ( 65 < getdvarflaot( #"cg_fov" ) )
        zacklodscalerigid( 0.65, 0.64 );
    else
        zacklodscalerigid( 1, 0.64 );

    level thread buried_watch_for_fov_change();
}

main_end()
{

}

buried_watch_for_fov_change()
{
    self endon( "disconnect" );
    previous_fov = getdvarflaot( #"cg_fov" );

    while ( true )
    {
        current_fov = getdvarflaot( #"cg_fov" );

        if ( current_fov != previous_fov )
        {
            if ( current_fov <= 65 )
                setdvarfloat( "r_lodScaleRigid", 1 );
            else
                setdvarfloat( "r_lodScaleRigid", 0.65 );

            previous_fov = current_fov;
        }

        wait 1;
    }
}
