// T6 GSC SOURCE
// Decompiled by https://github.com/xensik/gsc-tool
#include codescripts\character;
#include character\c_zom_tomb_german_1a;
#include character\c_zom_tomb_german_1a_nohat;
#include character\c_zom_tomb_german_2b;
#include character\c_zom_tomb_german_bare;
#include character\c_zom_tomb_german_bare_nohat;

#using_animtree("zm_tomb_basic");

reference_anims_from_animtree()
{
    dummy_anim_ref = %ai_zombie_idle_v1_delta;
    dummy_anim_ref = %ai_zombie_idle_crawl_delta;
    dummy_anim_ref = %ai_zombie_walk_v1;
    dummy_anim_ref = %ai_zombie_walk_v2;
    dummy_anim_ref = %ai_zombie_walk_v3;
    dummy_anim_ref = %ai_zombie_walk_v4;
    dummy_anim_ref = %ai_zombie_walk_v6;
    dummy_anim_ref = %ai_zombie_walk_v7;
    dummy_anim_ref = %ai_zombie_walk_v9;
    dummy_anim_ref = %ai_zombie_crawl;
    dummy_anim_ref = %ai_zombie_crawl_v1;
    dummy_anim_ref = %ai_zombie_crawl_v2;
    dummy_anim_ref = %ai_zombie_crawl_v3;
    dummy_anim_ref = %ai_zombie_crawl_v4;
    dummy_anim_ref = %ai_zombie_crawl_v5;
    dummy_anim_ref = %ai_zombie_walk_fast_v1;
    dummy_anim_ref = %ai_zombie_walk_fast_v2;
    dummy_anim_ref = %ai_zombie_walk_fast_v3;
    dummy_anim_ref = %ai_zombie_run_v2;
    dummy_anim_ref = %ai_zombie_run_v4;
    dummy_anim_ref = %ai_zombie_run_v3;
    dummy_anim_ref = %ai_zombie_sprint_v1;
    dummy_anim_ref = %ai_zombie_sprint_v2;
    dummy_anim_ref = %ai_zombie_crawl_sprint;
    dummy_anim_ref = %ai_zombie_crawl_sprint_1;
    dummy_anim_ref = %ai_zombie_crawl_sprint_2;
    dummy_anim_ref = %ai_zombie_fast_sprint_01;
    dummy_anim_ref = %ai_zombie_fast_sprint_02;
    dummy_anim_ref = %ai_zombie_walk_on_hands_a;
    dummy_anim_ref = %ai_zombie_walk_on_hands_b;
    dummy_anim_ref = %ai_zombie_attack_v2;
    dummy_anim_ref = %ai_zombie_attack_v4;
    dummy_anim_ref = %ai_zombie_attack_v6;
    dummy_anim_ref = %ai_zombie_attack_v1;
    dummy_anim_ref = %ai_zombie_attack_forward_v1;
    dummy_anim_ref = %ai_zombie_attack_forward_v2;
    dummy_anim_ref = %ai_zombie_walk_attack_v1;
    dummy_anim_ref = %ai_zombie_walk_attack_v2;
    dummy_anim_ref = %ai_zombie_walk_attack_v3;
    dummy_anim_ref = %ai_zombie_walk_attack_v4;
    dummy_anim_ref = %ai_zombie_run_attack_v1;
    dummy_anim_ref = %ai_zombie_run_attack_v2;
    dummy_anim_ref = %ai_zombie_run_attack_v3;
    dummy_anim_ref = %ai_zombie_attack_crawl;
    dummy_anim_ref = %ai_zombie_attack_crawl_lunge;
    dummy_anim_ref = %ai_zombie_walk_on_hands_shot_a;
    dummy_anim_ref = %ai_zombie_walk_on_hands_shot_b;
    dummy_anim_ref = %ai_zombie_taunts_4;
    dummy_anim_ref = %ai_zombie_taunts_7;
    dummy_anim_ref = %ai_zombie_taunts_9;
    dummy_anim_ref = %ai_zombie_taunts_5b;
    dummy_anim_ref = %ai_zombie_taunts_5c;
    dummy_anim_ref = %ai_zombie_taunts_5d;
    dummy_anim_ref = %ai_zombie_taunts_5e;
    dummy_anim_ref = %ai_zombie_taunts_5f;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_1_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_2_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_3_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_4_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_5_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_6_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_1_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_2_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_3_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_4_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_5_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_6_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_1_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_2_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_3_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_4_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_5_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_6_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_1_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_2_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_3_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_4_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_5_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_6_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_1_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_2_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_3_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_4_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_5_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_6_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_1_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_2_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_3_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_4_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_5_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_6_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_1_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_2_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_3_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_4_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_5_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_6_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_1_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_2_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_3_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_4_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_5_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_6_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_1_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_2_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_3_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_4_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_5_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_6_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_1_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_2_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_3_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_4_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_5_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_6_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_1_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_2_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_3_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_4_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_5_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_6_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_1_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_2_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_3_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_4_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_5_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_6_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_1_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_2_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_3_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_4_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_5_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_6_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_1_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_2_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_3_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_4_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_5_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_6_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_1_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_2_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_3_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_4_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_5_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_6_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_1_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_2_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_3_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_4_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_5_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_6_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_1_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_2_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_3_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_4_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_5_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_6_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_1_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_2_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_3_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_4_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_5_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_6_pull;
    dummy_anim_ref = %ai_zombie_window_attack_arm_l_out;
    dummy_anim_ref = %ai_zombie_window_attack_arm_r_out;
    dummy_anim_ref = %ai_zombie_traverse_ground_v1_deathinside;
    dummy_anim_ref = %ai_zombie_traverse_ground_v1_deathinside_alt;
    dummy_anim_ref = %ai_zombie_traverse_ground_v1_deathoutside;
    dummy_anim_ref = %ai_zombie_traverse_ground_v1_deathoutside_alt;
    dummy_anim_ref = %ai_zombie_traverse_ground_dugup;
    dummy_anim_ref = %ch_dazed_a_death;
    dummy_anim_ref = %ch_dazed_b_death;
    dummy_anim_ref = %ch_dazed_c_death;
    dummy_anim_ref = %ch_dazed_d_death;
    dummy_anim_ref = %ai_zombie_crawl_death_v1;
    dummy_anim_ref = %ai_zombie_crawl_death_v2;
    dummy_anim_ref = %ai_zombie_traverse_v1;
    dummy_anim_ref = %ai_zombie_traverse_v2;
    dummy_anim_ref = %ai_zombie_traverse_v5;
    dummy_anim_ref = %ai_zombie_traverse_v6;
    dummy_anim_ref = %ai_zombie_traverse_v7;
    dummy_anim_ref = %ai_zombie_traverse_crawl_v1;
    dummy_anim_ref = %ai_zombie_traverse_v4;
    dummy_anim_ref = %ai_zombie_barricade_enter_l;
    dummy_anim_ref = %ai_zombie_barricade_enter_r;
    dummy_anim_ref = %ai_zombie_barricade_enter_m_nolegs;
    dummy_anim_ref = %ai_zombie_barricade_enter_m_v1;
    dummy_anim_ref = %ai_zombie_barricade_enter_m_v2;
    dummy_anim_ref = %ai_zombie_barricade_enter_m_v3;
    dummy_anim_ref = %ai_zombie_barricade_enter_m_v4;
    dummy_anim_ref = %ai_zombie_barricade_enter_m_v5;
    dummy_anim_ref = %ai_zombie_barricade_enter_m_v6;
    dummy_anim_ref = %ai_zombie_barricade_enter_m_v7;
    dummy_anim_ref = %ai_zombie_barricade_enter_run_l;
    dummy_anim_ref = %ai_zombie_barricade_enter_run_r;
    dummy_anim_ref = %ai_zombie_barricade_enter_sprint_l;
    dummy_anim_ref = %ai_zombie_barricade_enter_sprint_r;
    dummy_anim_ref = %ai_zombie_crawl_barricade_enter_l;
    dummy_anim_ref = %ai_zombie_crawl_barricade_enter_r;
    dummy_anim_ref = %ai_zombie_crawl_barricade_enter_run_l;
    dummy_anim_ref = %ai_zombie_crawl_barricade_enter_run_r;
    dummy_anim_ref = %ai_zombie_crawl_barricade_enter_sprint_l;
    dummy_anim_ref = %ai_zombie_crawl_barricade_enter_sprint_r;
    dummy_anim_ref = %ai_zombie_jump_down_markiv_front;
    dummy_anim_ref = %ai_zombie_jump_down_markiv_leftfront;
    dummy_anim_ref = %ai_zombie_jump_down_markiv_leftmid;
    dummy_anim_ref = %ai_zombie_jump_down_markiv_leftrear;
    dummy_anim_ref = %ai_zombie_jump_down_markiv_rear;
    dummy_anim_ref = %ai_zombie_jump_down_markiv_rightfront;
    dummy_anim_ref = %ai_zombie_jump_down_markiv_rightmid;
    dummy_anim_ref = %ai_zombie_jump_down_markiv_rightrear;
    dummy_anim_ref = %ai_zombie_jump_up_markiv_front;
    dummy_anim_ref = %ai_zombie_jump_up_markiv_leftfront;
    dummy_anim_ref = %ai_zombie_jump_up_markiv_leftmid;
    dummy_anim_ref = %ai_zombie_jump_up_markiv_leftrear;
    dummy_anim_ref = %ai_zombie_jump_up_markiv_rear;
    dummy_anim_ref = %ai_zombie_jump_up_markiv_rightfront;
    dummy_anim_ref = %ai_zombie_jump_up_markiv_rightmid;
    dummy_anim_ref = %ai_zombie_jump_up_markiv_rightrear;
    dummy_anim_ref = %ai_zombie_jump_up_onto_markiv_rear;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_onto_markiv_rear;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_markiv_front;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_markiv_leftfront;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_markiv_leftmid;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_markiv_leftrear;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_markiv_rear;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_markiv_rightfront;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_markiv_rightmid;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_markiv_rightrear;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_markiv_front;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_markiv_leftfront;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_markiv_leftmid;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_markiv_leftrear;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_markiv_rear;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_markiv_rightfront;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_markiv_rightmid;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_markiv_rightrear;
    dummy_anim_ref = %ai_zombie_jump_across_120;
    dummy_anim_ref = %ai_zombie_jump_down_48;
    dummy_anim_ref = %ai_zombie_jump_down_72;
    dummy_anim_ref = %ai_zombie_jump_down_96;
    dummy_anim_ref = %ai_zombie_jump_down_127;
    dummy_anim_ref = %ai_zombie_jump_up_48;
    dummy_anim_ref = %ai_zombie_jump_up_96;
    dummy_anim_ref = %ai_zombie_jump_up_127;
    dummy_anim_ref = %ai_zombie_crawl_jump_across_120;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_48;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_72;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_96;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_127;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_48;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_96;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_127;
    dummy_anim_ref = %ai_zombie_traverse_alcove_40;
    dummy_anim_ref = %ai_zombie_traverse_alcove_56;
    dummy_anim_ref = %ai_zombie_traverse_alcove_96;
    dummy_anim_ref = %ai_zombie_traverse_scaffold_72;
    dummy_anim_ref = %ai_zombie_traverse_scaffold_84;
    dummy_anim_ref = %ai_zombie_traverse_scaffold_100;
    dummy_anim_ref = %ai_zombie_crawler_traverse_scaffold_72;
    dummy_anim_ref = %ai_zombie_crawler_traverse_scaffold_84;
    dummy_anim_ref = %ai_zombie_crawler_traverse_scaffold_100;
    dummy_anim_ref = %ai_zombie_jump_down_dlc4_trench_wall_96;
    dummy_anim_ref = %ai_zombie_jump_down_dlc4_trench_wall_112;
    dummy_anim_ref = %ai_zombie_jump_down_dlc4_trench_wall_120;
    dummy_anim_ref = %ai_zombie_jump_up_dlc4_trench_wall_140;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_dlc4_trench_wall_96;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_dlc4_trench_wall_112;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_dlc4_trench_wall_120;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_dlc4_trench_wall_140;
    dummy_anim_ref = %ai_zombie_vaultover_barbedwire;
    dummy_anim_ref = %ai_zombie_vaultover_barbedwire_24;
    dummy_anim_ref = %ai_zombie_crawl_vaultover_barbedwire;
    dummy_anim_ref = %ai_zombie_crawl_vaultover_barbedwire_24;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_church;
    dummy_anim_ref = %ai_zombie_jump_down_church;
    dummy_anim_ref = %ai_zombie_thundergun_hit;
    dummy_anim_ref = %ai_zombie_thundergun_hit_armslegsforward;
    dummy_anim_ref = %ai_zombie_thundergun_hit_doublebounce;
    dummy_anim_ref = %ai_zombie_thundergun_hit_forwardtoface;
    dummy_anim_ref = %ai_zombie_thundergun_hit_upontoback;
    dummy_anim_ref = %ai_zombie_thundergun_hit_stumblefall;
    dummy_anim_ref = %ai_zombie_thundergun_hit_deadfallknee;
    dummy_anim_ref = %ai_zombie_thundergun_hit_flatonback;
    dummy_anim_ref = %ai_zombie_thundergun_hit_legsout_right;
    dummy_anim_ref = %ai_zombie_thundergun_hit_legsout_left;
    dummy_anim_ref = %ai_zombie_thundergun_hit_jackiespin_left;
    dummy_anim_ref = %ai_zombie_thundergun_hit_jackiespin_right;
    dummy_anim_ref = %ai_zombie_thundergun_hit_faceplant;
    dummy_anim_ref = %ai_zombie_thundergun_getup;
    dummy_anim_ref = %ai_zombie_thundergun_getup_a;
    dummy_anim_ref = %ai_zombie_thundergun_getup_b;
    dummy_anim_ref = %ai_zombie_thundergun_getup_c;
    dummy_anim_ref = %ai_zombie_thundergun_getup_quick_a;
    dummy_anim_ref = %ai_zombie_thundergun_getup_quick_b;
    dummy_anim_ref = %ai_zombie_thundergun_getup_quick_c;
    dummy_anim_ref = %ai_zombie_thundergun_sprinter_getup_a;
    dummy_anim_ref = %ai_zombie_thundergun_sprinter_getup_b;
    dummy_anim_ref = %ai_zombie_thundergun_sprinter_getup_c;
    dummy_anim_ref = %ai_zombie_dlc4_tesla_death_a;
    dummy_anim_ref = %ai_zombie_dlc4_tesla_death_b;
    dummy_anim_ref = %ai_zombie_dlc4_tesla_death_c;
    dummy_anim_ref = %ai_zombie_dlc4_tesla_death_d;
    dummy_anim_ref = %ai_zombie_dlc4_tesla_death_e;
    dummy_anim_ref = %ai_zombie_dlc4_tesla_crawl_death_a;
    dummy_anim_ref = %ai_zombie_dlc4_tesla_crawl_death_b;
    dummy_anim_ref = %ai_zombie_dlc4_freeze_death_a;
    dummy_anim_ref = %ai_zombie_dlc4_freeze_death_b;
    dummy_anim_ref = %ai_zombie_dlc4_freeze_death_c;
    dummy_anim_ref = %ai_zombie_dlc4_freeze_death_d;
    dummy_anim_ref = %ai_zombie_dlc4_freeze_death_e;
    dummy_anim_ref = %ai_zombie_death_icestaff_a;
    dummy_anim_ref = %ai_zombie_death_icestaff_b;
    dummy_anim_ref = %ai_zombie_death_icestaff_c;
    dummy_anim_ref = %ai_zombie_death_icestaff_d;
    dummy_anim_ref = %ai_zombie_death_icestaff_e;
    dummy_anim_ref = %ai_zombie_dlc4_crawl_freeze_death_01;
    dummy_anim_ref = %ai_zombie_dlc4_crawl_freeze_death_02;
    dummy_anim_ref = %ai_zombie_afterlife_stun_a;
    dummy_anim_ref = %ai_zombie_afterlife_stun_b;
    dummy_anim_ref = %ai_zombie_afterlife_stun_c;
    dummy_anim_ref = %ai_zombie_afterlife_stun_d;
    dummy_anim_ref = %ai_zombie_afterlife_stun_e;
    dummy_anim_ref = %ai_zombie_airstaff_death_vacuumed_a;
    dummy_anim_ref = %ai_zombie_airstaff_death_vacuumed_b;
    dummy_anim_ref = %ai_zombie_airstaff_death_vacuumed_c;
    dummy_anim_ref = %ai_zombie_airstaff_death_vacuumed_midair_a;
    dummy_anim_ref = %ai_zombie_airstaff_death_vacuumed_midair_b;
    dummy_anim_ref = %ai_zombie_airstaff_death_vacuumed_midair_c;
    dummy_anim_ref = %ai_zombie_airstaff_death_vacuumed_midair_d;
    dummy_anim_ref = %ai_zombie_firestaff_death_walking_a;
    dummy_anim_ref = %ai_zombie_firestaff_death_walking_b;
    dummy_anim_ref = %ai_zombie_firestaff_death_walking_c;
    dummy_anim_ref = %ai_zombie_firestaff_death_collapse_a;
    dummy_anim_ref = %ai_zombie_firestaff_death_collapse_b;
    dummy_anim_ref = %ai_zombie_grabbed_by_mech;
}

main()
{
    self.accuracy = 1;
    self.animstatedef = "zm_tomb_basic.asd";
    self.animtree = "zm_tomb_basic.atr";
    self.csvinclude = "";
    self.demolockonhighlightdistance = 100;
    self.demolockonviewheightoffset1 = 60;
    self.demolockonviewheightoffset2 = 30;
    self.demolockonviewpitchmax1 = 60;
    self.demolockonviewpitchmax2 = 60;
    self.demolockonviewpitchmin1 = -15;
    self.demolockonviewpitchmin2 = -5;
    self.footstepfxtable = "";
    self.footstepprepend = "";
    self.footstepscriptcallback = 0;
    self.grenadeammo = 0;
    self.grenadeweapon = "";
    self.health = 200;
    self.precachescript = "";
    self.secondaryweapon = "";
    self.sidearm = "";
    self.subclass = "regular";
    self.team = "axis";
    self.type = "zombie";
    self.weapon = "";
    self setengagementmindist( 0.0, 0.0 );
    self setengagementmaxdist( 100.0, 300.0 );
    randchar = codescripts\character::get_random_character( 6 );

    switch ( randchar )
    {
        case "0":
            character\c_zom_tomb_german_1a::main();
            break;
        case "1":
            character\c_zom_tomb_german_1a_nohat::main();
            break;
        case "2":
            character\c_zom_tomb_german_2b::main();
            break;
        case "3":
            character\c_zom_tomb_german_bare::main();
            break;
        case "4":
            character\c_zom_tomb_german_bare_nohat::main();
            break;
        case "5":
            character\c_zom_tomb_german_bare_nohat::main();
            break;
    }

    self setcharacterindex( randchar );
}

spawner()
{
    self setspawnerteam( "axis" );
}

precache( ai_index )
{
    level thread reference_anims_from_animtree();
    precacheanimstatedef( ai_index, -1, "zm_tomb_basic" );
    character\c_zom_tomb_german_1a::precache();
    character\c_zom_tomb_german_1a_nohat::precache();
    character\c_zom_tomb_german_2b::precache();
    character\c_zom_tomb_german_bare::precache();
    character\c_zom_tomb_german_bare_nohat::precache();
    character\c_zom_tomb_german_bare_nohat::precache();
}
