// T6 GSC SOURCE
// Decompiled by https://github.com/xensik/gsc-tool
#include codescripts\character;
#include character\c_zom_zombie_civ_shorts;
#include character\c_zom_zombie_civ_shorts2;
#include character\c_zom_zombie_civ_shorts3;
#include character\c_zom_zombie_civ_shorts4;
#include character\c_zom_zombie_civ_shorts5;
#include character\c_zom_zombie_civ_shorts6;

#using_animtree("zm_highrise_basic");

reference_anims_from_animtree()
{
    dummy_anim_ref = %ai_zombie_idle_v1_delta;
    dummy_anim_ref = %ai_zombie_idle_crawl_delta;
    dummy_anim_ref = %ai_zombie_walk_v1;
    dummy_anim_ref = %ai_zombie_walk_v2;
    dummy_anim_ref = %ai_zombie_walk_v3;
    dummy_anim_ref = %ai_zombie_walk_v4;
    dummy_anim_ref = %ai_zombie_walk_v6;
    dummy_anim_ref = %ai_zombie_walk_v7;
    dummy_anim_ref = %ai_zombie_walk_v9;
    dummy_anim_ref = %ai_zombie_crawl;
    dummy_anim_ref = %ai_zombie_crawl_v1;
    dummy_anim_ref = %ai_zombie_crawl_v2;
    dummy_anim_ref = %ai_zombie_crawl_v3;
    dummy_anim_ref = %ai_zombie_crawl_v4;
    dummy_anim_ref = %ai_zombie_crawl_v5;
    dummy_anim_ref = %ai_zombie_walk_fast_v1;
    dummy_anim_ref = %ai_zombie_walk_fast_v2;
    dummy_anim_ref = %ai_zombie_walk_fast_v3;
    dummy_anim_ref = %ai_zombie_run_v2;
    dummy_anim_ref = %ai_zombie_run_v4;
    dummy_anim_ref = %ai_zombie_run_v3;
    dummy_anim_ref = %ai_zombie_sprint_v1;
    dummy_anim_ref = %ai_zombie_sprint_v2;
    dummy_anim_ref = %ai_zombie_crawl_sprint;
    dummy_anim_ref = %ai_zombie_crawl_sprint_1;
    dummy_anim_ref = %ai_zombie_crawl_sprint_2;
    dummy_anim_ref = %ai_zombie_fast_sprint_01;
    dummy_anim_ref = %ai_zombie_fast_sprint_02;
    dummy_anim_ref = %ai_zombie_walk_on_hands_a;
    dummy_anim_ref = %ai_zombie_walk_on_hands_b;
    dummy_anim_ref = %ai_zombie_attack_v2;
    dummy_anim_ref = %ai_zombie_attack_v4;
    dummy_anim_ref = %ai_zombie_attack_v6;
    dummy_anim_ref = %ai_zombie_attack_v1;
    dummy_anim_ref = %ai_zombie_attack_forward_v1;
    dummy_anim_ref = %ai_zombie_attack_forward_v2;
    dummy_anim_ref = %ai_zombie_walk_attack_v1;
    dummy_anim_ref = %ai_zombie_walk_attack_v2;
    dummy_anim_ref = %ai_zombie_walk_attack_v3;
    dummy_anim_ref = %ai_zombie_walk_attack_v4;
    dummy_anim_ref = %ai_zombie_run_attack_v1;
    dummy_anim_ref = %ai_zombie_run_attack_v2;
    dummy_anim_ref = %ai_zombie_run_attack_v3;
    dummy_anim_ref = %ai_zombie_attack_crawl;
    dummy_anim_ref = %ai_zombie_attack_crawl_lunge;
    dummy_anim_ref = %ai_zombie_walk_on_hands_shot_a;
    dummy_anim_ref = %ai_zombie_walk_on_hands_shot_b;
    dummy_anim_ref = %ai_zombie_spets_sidestep_left_a;
    dummy_anim_ref = %ai_zombie_spets_sidestep_left_b;
    dummy_anim_ref = %ai_zombie_spets_sidestep_right_a;
    dummy_anim_ref = %ai_zombie_spets_sidestep_right_b;
    dummy_anim_ref = %ai_zombie_spets_roll_a;
    dummy_anim_ref = %ai_zombie_spets_roll_b;
    dummy_anim_ref = %ai_zombie_spets_roll_c;
    dummy_anim_ref = %ai_zombie_taunts_4;
    dummy_anim_ref = %ai_zombie_taunts_7;
    dummy_anim_ref = %ai_zombie_taunts_9;
    dummy_anim_ref = %ai_zombie_taunts_5b;
    dummy_anim_ref = %ai_zombie_taunts_5c;
    dummy_anim_ref = %ai_zombie_taunts_5d;
    dummy_anim_ref = %ai_zombie_taunts_5e;
    dummy_anim_ref = %ai_zombie_taunts_5f;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_1_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_2_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_3_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_4_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_5_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_6_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_1_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_2_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_3_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_4_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_5_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_6_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_1_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_2_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_3_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_4_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_5_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_6_grab;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_1_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_2_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_3_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_4_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_5_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_6_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_1_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_2_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_3_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_4_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_5_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_6_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_1_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_2_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_3_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_4_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_5_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_6_hold;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_1_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_2_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_3_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_4_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_5_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_m_6_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_1_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_2_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_3_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_4_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_5_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_r_6_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_1_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_2_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_3_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_4_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_5_pull;
    dummy_anim_ref = %ai_zombie_boardtear_aligned_l_6_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_1_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_2_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_3_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_4_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_5_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_6_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_1_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_2_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_3_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_4_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_5_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_6_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_1_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_2_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_3_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_4_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_5_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_6_grab;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_1_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_2_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_3_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_4_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_5_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_6_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_1_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_2_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_3_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_4_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_5_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_6_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_1_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_2_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_3_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_4_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_5_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_6_hold;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_1_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_2_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_3_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_4_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_5_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_m_6_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_1_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_2_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_3_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_4_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_5_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_r_6_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_1_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_2_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_3_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_4_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_5_pull;
    dummy_anim_ref = %ai_zombie_crawl_boardtear_aligned_l_6_pull;
    dummy_anim_ref = %ai_zombie_window_attack_arm_l_out;
    dummy_anim_ref = %ai_zombie_window_attack_arm_r_out;
    dummy_anim_ref = %ai_zombie_traverse_ground_v1_walk;
    dummy_anim_ref = %ai_zombie_traverse_ground_v2_walk_alta;
    dummy_anim_ref = %ai_zombie_traverse_ground_v1_run;
    dummy_anim_ref = %ai_zombie_traverse_ground_climbout_fast;
    dummy_anim_ref = %ai_zombie_traverse_ground_v1_deathinside;
    dummy_anim_ref = %ai_zombie_traverse_ground_v1_deathinside_alt;
    dummy_anim_ref = %ai_zombie_traverse_ground_v1_deathoutside;
    dummy_anim_ref = %ai_zombie_traverse_ground_v1_deathoutside_alt;
    dummy_anim_ref = %ai_zombie_ceiling_attack_01;
    dummy_anim_ref = %ai_zombie_ceiling_attack_02;
    dummy_anim_ref = %ai_zombie_ceiling_emerge_01;
    dummy_anim_ref = %ai_zombie_ceiling_death;
    dummy_anim_ref = %ai_zombie_ceiling_dropdown_01;
    dummy_anim_ref = %ai_zombie_ceiling_fall_loop;
    dummy_anim_ref = %ai_zombie_ceiling_fall_land;
    dummy_anim_ref = %ai_zombie_ceiling_fall_land_02;
    dummy_anim_ref = %ch_dazed_a_death;
    dummy_anim_ref = %ch_dazed_b_death;
    dummy_anim_ref = %ch_dazed_c_death;
    dummy_anim_ref = %ch_dazed_d_death;
    dummy_anim_ref = %ai_zombie_crawl_death_v1;
    dummy_anim_ref = %ai_zombie_crawl_death_v2;
    dummy_anim_ref = %ai_zombie_traverse_v1;
    dummy_anim_ref = %ai_zombie_traverse_v2;
    dummy_anim_ref = %ai_zombie_traverse_v5;
    dummy_anim_ref = %ai_zombie_traverse_v6;
    dummy_anim_ref = %ai_zombie_traverse_v7;
    dummy_anim_ref = %ai_zombie_traverse_crawl_v1;
    dummy_anim_ref = %ai_zombie_traverse_v4;
    dummy_anim_ref = %ai_zombie_barricade_enter_l;
    dummy_anim_ref = %ai_zombie_barricade_enter_r;
    dummy_anim_ref = %ai_zombie_barricade_enter_m_nolegs;
    dummy_anim_ref = %ai_zombie_barricade_enter_m_v1;
    dummy_anim_ref = %ai_zombie_barricade_enter_m_v2;
    dummy_anim_ref = %ai_zombie_barricade_enter_m_v3;
    dummy_anim_ref = %ai_zombie_barricade_enter_m_v4;
    dummy_anim_ref = %ai_zombie_barricade_enter_m_v5;
    dummy_anim_ref = %ai_zombie_barricade_enter_m_v6;
    dummy_anim_ref = %ai_zombie_barricade_enter_m_v7;
    dummy_anim_ref = %ai_zombie_barricade_enter_run_l;
    dummy_anim_ref = %ai_zombie_barricade_enter_run_r;
    dummy_anim_ref = %ai_zombie_barricade_enter_sprint_l;
    dummy_anim_ref = %ai_zombie_barricade_enter_sprint_r;
    dummy_anim_ref = %ai_zombie_crawl_barricade_enter_l;
    dummy_anim_ref = %ai_zombie_crawl_barricade_enter_r;
    dummy_anim_ref = %ai_zombie_crawl_barricade_enter_run_l;
    dummy_anim_ref = %ai_zombie_crawl_barricade_enter_run_r;
    dummy_anim_ref = %ai_zombie_crawl_barricade_enter_sprint_l;
    dummy_anim_ref = %ai_zombie_crawl_barricade_enter_sprint_r;
    dummy_anim_ref = %ai_zombie_slipslide_collapse;
    dummy_anim_ref = %ai_zombie_walk_slipslide;
    dummy_anim_ref = %ai_zombie_walk_slipslide_a;
    dummy_anim_ref = %ai_zombie_run_slipslide;
    dummy_anim_ref = %ai_zombie_run_slipslide_a;
    dummy_anim_ref = %ai_zombie_sprint_slipslide;
    dummy_anim_ref = %ai_zombie_sprint_slipslide_a;
    dummy_anim_ref = %ai_zombie_stand_slipslide_recover;
    dummy_anim_ref = %ai_zombie_crawl_slipslide_slow;
    dummy_anim_ref = %ai_zombie_crawl_slipslide_fast;
    dummy_anim_ref = %ai_zombie_crawl_slipslide_recover;
    dummy_anim_ref = %ai_zombie_jump_down_40;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_40;
    dummy_anim_ref = %ai_zombie_jump_down_48;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_48;
    dummy_anim_ref = %ai_zombie_jump_down_96;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_96;
    dummy_anim_ref = %ai_zombie_jump_down_120;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_120;
    dummy_anim_ref = %ai_zombie_jump_down_127;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_127;
    dummy_anim_ref = %ai_zombie_jump_down_176;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_176;
    dummy_anim_ref = %ai_zombie_jump_down_184;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_184;
    dummy_anim_ref = %ai_zombie_jump_down_190;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_189;
    dummy_anim_ref = %ai_zombie_jump_up_127;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_127;
    dummy_anim_ref = %ai_zombie_jump_up_175;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_175;
    dummy_anim_ref = %ai_zombie_jump_up_grabbed_48;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_grabbed_48;
    dummy_anim_ref = %ai_zombie_jump_up_grabbed_190;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_grabbed_190;
    dummy_anim_ref = %ai_zombie_crawl_traverse_48;
    dummy_anim_ref = %ai_zombie_traverse_48;
    dummy_anim_ref = %ai_zombie_traverse_dierise_escape_corridor;
    dummy_anim_ref = %ai_zombie_traverse_round_counter_to_stools;
    dummy_anim_ref = %ai_zombie_traverse_round_counter_from_stools;
    dummy_anim_ref = %ai_zombie_traverse_dierise_chrest_interior_high_to_low;
    dummy_anim_ref = %ai_zombie_traverse_dierise_chrest_interior_low_to_high;
    dummy_anim_ref = %ai_zombie_traverse_dierise_chrest_interior_alt_high_to_low;
    dummy_anim_ref = %ai_zombie_traverse_dierise_chrest_interior_alt_low_to_high;
    dummy_anim_ref = %ai_zombie_traverse_dierise_chrest_gap;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_chrest_gap;
    dummy_anim_ref = %ai_zombie_jump_up_grabbed_antenna;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_grabbed_antenna;
    dummy_anim_ref = %ai_zombie_jump_up_sewing;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_sewing;
    dummy_anim_ref = %ai_zombie_traverse_dierise_1_high_to_low;
    dummy_anim_ref = %ai_zombie_traverse_dierise_2_high_to_low;
    dummy_anim_ref = %ai_zombie_traverse_dierise_2_low_to_high;
    dummy_anim_ref = %ai_zombie_traverse_dierise_3_high_to_low;
    dummy_anim_ref = %ai_zombie_traverse_dierise_3_low_to_high;
    dummy_anim_ref = %ai_zombie_traverse_dierise_4_high_to_low;
    dummy_anim_ref = %ai_zombie_traverse_dierise_4_low_to_high;
    dummy_anim_ref = %ai_zombie_traverse_dierise_5_high_to_low;
    dummy_anim_ref = %ai_zombie_traverse_dierise_5_low_to_high;
    dummy_anim_ref = %ai_zombie_traverse_dierise_6_high_to_low;
    dummy_anim_ref = %ai_zombie_traverse_dierise_6_low_to_high;
    dummy_anim_ref = %ai_zombie_traverse_dierise_7_high_to_low;
    dummy_anim_ref = %ai_zombie_traverse_dierise_7_low_to_high;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap1_from_antenna;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap4a_slide_down_beam;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap4b_from_roof;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap6_high_to_low;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap6_low_to_high;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap7_from_top_ledge;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap7_to_top_ledge;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap8_high_to_low;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap15a_from_girder;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap15b_from_girder;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap15f_low_to_high;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap15g_high_to_low;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap16a_high_to_low;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap16a_low_to_high;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap16b_high_to_low;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap16b_low_to_high;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap17a_high_to_low;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap17c_high_to_low;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap17c_low_to_high;
    dummy_anim_ref = %ai_zombie_traverse_dierise_gap18_high_to_low;
    dummy_anim_ref = %ai_zombie_crawl_jump_down_to_elevator_roof;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_from_elevator_roof;
    dummy_anim_ref = %ai_zombie_jump_down_to_elevator_roof;
    dummy_anim_ref = %ai_zombie_jump_up_from_elevator_roof;
    dummy_anim_ref = %ai_zombie_climb_elevator;
    dummy_anim_ref = %ai_zombie_crawl_traverse_round_counter_to_stools;
    dummy_anim_ref = %ai_zombie_crawl_traverse_round_counter_from_stools;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_chrest_interior_high_to_low;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_chrest_interior_low_to_high;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_chrest_interior_alt_high_to_low;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_chrest_interior_alt_low_to_high;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_1_high_to_low;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_2_high_to_low;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_2_low_to_high;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_3_high_to_low;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_3_low_to_high;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_4_high_to_low;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_4_low_to_high;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_5_high_to_low;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_5_low_to_high;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_6_high_to_low;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_6_low_to_high;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_7_low_to_high;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_7_high_to_low;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap1_from_antenna;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap4a_slide_down_beam;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap4b_from_roof;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap6_high_to_low;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap6_low_to_high;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap7_from_top_ledge;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap7_to_top_ledge;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap8_high_to_low;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap15a_from_girder;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap15b_from_girder;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap15f_low_to_high;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap15f_high_to_low;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap15g_high_to_low;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap15g_low_to_high;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap16a_high_to_low;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap16a_low_to_high;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap16b_high_to_low;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap16b_low_to_high;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap17a_high_to_low;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap17a_low_to_high;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap17c_high_to_low;
    dummy_anim_ref = %ai_zombie_crawl_traverse_dierise_gap18_high_to_low;
    dummy_anim_ref = %ai_zombie_riser_elevator_from_floor;
    dummy_anim_ref = %ai_zombie_riser_elevator_from_ceiling;
}

main()
{
    self.accuracy = 1;
    self.animstatedef = "zm_highrise_basic.asd";
    self.animtree = "zm_highrise_basic.atr";
    self.csvinclude = "";
    self.demolockonhighlightdistance = 100;
    self.demolockonviewheightoffset1 = 60;
    self.demolockonviewheightoffset2 = 30;
    self.demolockonviewpitchmax1 = 60;
    self.demolockonviewpitchmax2 = 60;
    self.demolockonviewpitchmin1 = -15;
    self.demolockonviewpitchmin2 = -5;
    self.footstepfxtable = "";
    self.footstepprepend = "";
    self.footstepscriptcallback = 0;
    self.grenadeammo = 0;
    self.grenadeweapon = "";
    self.health = 200;
    self.precachescript = "";
    self.secondaryweapon = "";
    self.sidearm = "";
    self.subclass = "regular";
    self.team = "axis";
    self.type = "zombie";
    self.weapon = "";
    self setengagementmindist( 0.0, 0.0 );
    self setengagementmaxdist( 100.0, 300.0 );
    randchar = codescripts\character::get_random_character( 6 );

    switch ( randchar )
    {
        case 0:
            character\c_zom_zombie_civ_shorts::main();
            break;
        case 1:
            character\c_zom_zombie_civ_shorts2::main();
            break;
        case 2:
            character\c_zom_zombie_civ_shorts3::main();
            break;
        case 3:
            character\c_zom_zombie_civ_shorts4::main();
            break;
        case 4:
            character\c_zom_zombie_civ_shorts5::main();
            break;
        case 5:
            character\c_zom_zombie_civ_shorts6::main();
            break;
    }

    self setcharacterindex( randchar );
}

spawner()
{
    self setspawnerteam( "axis" );
}

precache( ai_index )
{
    level thread reference_anims_from_animtree();
    precacheanimstatedef( ai_index, -1, "zm_highrise_basic" );
    character\c_zom_zombie_civ_shorts::precache();
    character\c_zom_zombie_civ_shorts2::precache();
    character\c_zom_zombie_civ_shorts3::precache();
    character\c_zom_zombie_civ_shorts4::precache();
    character\c_zom_zombie_civ_shorts5::precache();
    character\c_zom_zombie_civ_shorts6::precache();
}
