// T6 GSC SOURCE
// Decompiled by https://github.com/xensik/gsc-tool
#include character\c_zom_leaper;

#using_animtree("zm_highrise_leaper");

reference_anims_from_animtree()
{
    dummy_anim_ref = %ai_zombie_quad_idle;
    dummy_anim_ref = %ai_zombie_quad_idle_2;
    dummy_anim_ref = %ai_zombie_leaper_death_v1;
    dummy_anim_ref = %ai_zombie_leaper_death_v2;
    dummy_anim_ref = %ai_zombie_leaper_run_f;
    dummy_anim_ref = %ai_zombie_leaper_run_bounce;
    dummy_anim_ref = %ai_zombie_quad_crawl;
    dummy_anim_ref = %ai_zombie_quad_crawl_2;
    dummy_anim_ref = %ai_zombie_quad_crawl_3;
    dummy_anim_ref = %ai_zombie_quad_crawl_run;
    dummy_anim_ref = %ai_zombie_quad_crawl_run_2;
    dummy_anim_ref = %ai_zombie_quad_crawl_run_3;
    dummy_anim_ref = %ai_zombie_quad_crawl_run_4;
    dummy_anim_ref = %ai_zombie_quad_crawl_run_5;
    dummy_anim_ref = %ai_zombie_quad_crawl_sprint;
    dummy_anim_ref = %ai_zombie_quad_crawl_sprint_2;
    dummy_anim_ref = %ai_zombie_quad_crawl_sprint_3;
    dummy_anim_ref = %ai_zombie_quad_crawl_01;
    dummy_anim_ref = %ai_zombie_quad_crawl_02;
    dummy_anim_ref = %ai_zombie_quad_crawl_03;
    dummy_anim_ref = %ai_zombie_leaper_attack_v1;
    dummy_anim_ref = %ai_zombie_leaper_attack_v2;
    dummy_anim_ref = %ai_zombie_leaper_wall_traverse_l;
    dummy_anim_ref = %ai_zombie_leaper_wall_traverse_r;
    dummy_anim_ref = %ai_zombie_leaper_ceiling_traverse;
    dummy_anim_ref = %ai_leaper_traverse_dierise_barrier;
    dummy_anim_ref = %ai_zombie_jump_down_40;
    dummy_anim_ref = %ai_zombie_jump_down_48;
    dummy_anim_ref = %ai_zombie_jump_down_190;
    dummy_anim_ref = %ai_zombie_jump_down_184;
    dummy_anim_ref = %ai_zombie_jump_down_176;
    dummy_anim_ref = %ai_leaper_jump_down_120;
    dummy_anim_ref = %ai_zombie_jump_up_grabbed_48;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_grabbed_48;
    dummy_anim_ref = %ai_zombie_jump_down_96;
    dummy_anim_ref = %ai_zombie_jump_down_127;
    dummy_anim_ref = %ai_zombie_jump_up_127;
    dummy_anim_ref = %ai_leaper_jump_up_175;
    dummy_anim_ref = %ai_zombie_jump_up_grabbed_190;
    dummy_anim_ref = %ai_zombie_crawl_jump_up_grabbed_190;
    dummy_anim_ref = %ai_zombie_traverse_48;
    dummy_anim_ref = %ai_leaper_jump_up_sewing;
    dummy_anim_ref = %ai_leaper_dierise_ventfall_176;
    dummy_anim_ref = %ai_leaper_crawl_traverse_round_counter_from_stools;
    dummy_anim_ref = %ai_leaper_crawl_traverse_round_counter_to_stools;
    dummy_anim_ref = %ai_leaper_traverse_dierise_chrest_interior_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_chrest_interior_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_1_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_1_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_2_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_2_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_3_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_3_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_4_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_4_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_chrest_elevator_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_5_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_6_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_6_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_7_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_7_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap1_to_antenna;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap1_from_antenna;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap2_from_roof;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap2_to_roof;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap4b_to_roof;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap4b_from_roof;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap5a_from_conference;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap5a_to_conference;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap5b_from_conference;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap5b_to_conference;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap6_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap6_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap7_from_top_ledge;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap7_to_top_ledge;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap8_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap8_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap9_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap9_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap10_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap10_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap14a_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap14b_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap14c_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap14c_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap14d_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap14d_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap14e_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap14e_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap14f_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap14f_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap14g_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap14g_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap14h_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap14h_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap15a_from_girder;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap15b_from_girder;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap15f_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap15f_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap15g_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap15g_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap16a_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap16a_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap16b_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap16b_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap17a_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap17a_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap17c_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap17c_low_to_high;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap18_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap19_from_railing;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap19_to_railing;
    dummy_anim_ref = %ai_zombie_leaper_wall_traverse_l_large;
    dummy_anim_ref = %ai_zombie_leaper_wall_traverse_r_large;
    dummy_anim_ref = %ai_leaper_traverse_dierise_gap15c_low_to_high;
    dummy_anim_ref = %ai_zombie_jump_up_grabbed_190_dlc1;
    dummy_anim_ref = %ai_zombie_jump_up_grabbed_antenna;
    dummy_anim_ref = %ai_leaper_traverse_dierise_chrest_gap;
    dummy_anim_ref = %ai_zombie_leaper_traverse_dierise_green_ext_a;
    dummy_anim_ref = %ai_zombie_leaper_traverse_dierise_green_ext_b;
    dummy_anim_ref = %ai_zombie_leaper_traverse_dierise_green_ext_c;
    dummy_anim_ref = %ai_zombie_leaper_traverse_dierise_green_ext_d;
    dummy_anim_ref = %ai_zombie_leaper_traverse_dierise_green_ext_e;
    dummy_anim_ref = %ai_zombie_leaper_traverse_dierise_green_ext_f;
    dummy_anim_ref = %ai_zombie_leaper_traverse_dierise_bluegreen_antenna_to_escalator;
    dummy_anim_ref = %ai_leaper_traverse_shoestore;
    dummy_anim_ref = %ai_zombie_leaper_traverse_dierise_orange_ext_a_right;
    dummy_anim_ref = %ai_zombie_leaper_traverse_dierise_orange_ext_a_left;
    dummy_anim_ref = %ai_zombie_leaper_traverse_dierise_orange_ext_b_left;
    dummy_anim_ref = %ai_zombie_leaper_traverse_dierise_orange_ext_b_right;
    dummy_anim_ref = %ai_zombie_leaper_traverse_dierise_orange_ext_c;
    dummy_anim_ref = %ai_zombie_leaper_traverse_dierise_blue_ext_a;
    dummy_anim_ref = %ai_leaper_traverse_dierise_shaft1_to_bottom;
    dummy_anim_ref = %ai_leaper_traverse_dierise_shaft1_from_bottom;
    dummy_anim_ref = %ai_leaper_traverse_dierise_shaft2_to_bottom;
    dummy_anim_ref = %ai_leaper_traverse_dierise_shaft2_from_bottom;
    dummy_anim_ref = %ai_leaper_traverse_dierise_restaurant_in;
    dummy_anim_ref = %ai_leaper_traverse_dierise_ac_unit;
    dummy_anim_ref = %ai_leaper_traverse_dierise_chrest_interior_alt_high_to_low;
    dummy_anim_ref = %ai_leaper_traverse_dierise_chrest_interior_alt_low_to_high;
    dummy_anim_ref = %ai_zombie_leaper_traverse_dierise_green_ext_g;
    dummy_anim_ref = %ai_leaper_jump_down_to_elevator_roof;
    dummy_anim_ref = %ai_leaper_jump_up_from_elevator_roof;
    dummy_anim_ref = %ai_zombie_leaper_climb_elevator;
    dummy_anim_ref = %ai_zombie_crawl_slipslide_slow;
    dummy_anim_ref = %ai_zombie_crawl_slipslide_fast;
    dummy_anim_ref = %ai_zombie_crawl_slipslide_recover;
    dummy_anim_ref = %ai_zombie_leaper_elevator_from_ceiling;
    dummy_anim_ref = %ai_zombie_leaper_elevator_from_floor;
}

main()
{
    self.accuracy = 1;
    self.animstatedef = "zm_highrise_leaper.asd";
    self.animtree = "zm_highrise_leaper.atr";
    self.csvinclude = "";
    self.demolockonhighlightdistance = 100;
    self.demolockonviewheightoffset1 = 18;
    self.demolockonviewheightoffset2 = 8;
    self.demolockonviewpitchmax1 = 60;
    self.demolockonviewpitchmax2 = 60;
    self.demolockonviewpitchmin1 = 0;
    self.demolockonviewpitchmin2 = 0;
    self.footstepfxtable = "zm_leaper_footstepfxtable";
    self.footstepprepend = "";
    self.footstepscriptcallback = 0;
    self.grenadeammo = 0;
    self.grenadeweapon = "";
    self.health = 150;
    self.precachescript = "";
    self.secondaryweapon = "";
    self.sidearm = "";
    self.subclass = "regular";
    self.team = "axis";
    self.type = "zombie";
    self.weapon = "";
    self setengagementmindist( 0.0, 0.0 );
    self setengagementmaxdist( 100.0, 300.0 );
    character\c_zom_leaper::main();
    self setcharacterindex( 0 );
}

spawner()
{
    self setspawnerteam( "axis" );
}

precache( ai_index )
{
    level thread reference_anims_from_animtree();
    precacheanimstatedef( ai_index, -1, "zm_highrise_leaper" );
    character\c_zom_leaper::precache();
}
