// T6 GSC SOURCE
// Generated by https://github.com/xensik/gsc-tool
#include clientscripts\mp\_utility;
#include clientscripts\mp\_fx;

#using_animtree("zombie_springpad");

init_animtree()
{
    scriptmodelsuseanimtree( #animtree );
}
